### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by goerlibe**
- ~remove NodeType~
- organize imports
- unused code
- ~tiny GUI feature: close with CTRL+C from command line~

### CODE REVIEW

**Comment by goerlibe** [comment]
neither pycharm nor vs code can reliably find all usages of a class property (Node.type) or a class (NodeType)....
at least mypy picks up on it. I will have another look at this some other time...

**Comment by lukasrothenberger** [comment]
maybe create a PR for "tiny GUI feature: close with CTRL+C from command line" in the meantime?

**Comment by goerlibe** [comment]
> @goerlibe maybe create a PR for "tiny GUI feature: close with CTRL+C from command line" in the meantime?

moved to PR  #325

**Comment by goerlibe** [comment]
I suggest we fix the imports together with the planned formatting. 
So this PR now only contains the removal of unused code and can be merged :)

**Review by lukasrothenberger — APPROVED** [review]

**Pull request merged**
