### PR TITLE
Task Parallelism Detection: data sharing clause validation and simple alias detection

### PR DESCRIPTION
**Pull request by lukasrothenberger**
@aryamazaheri 

Hi Arya,
Please take a look over our latest changes, especially the newly added script, whenever it suits your schedule.
If the scripts aren´t in the correct location, please let me know.

Thanks a lot!

### CODE REVIEW

**Comment by lukasrothenberger** [comment]
@aryamazaheri 
Hi Arya,
I have included the discussed changes.

However, two checks are failing while building. The same error occured on my local machine and could be fixed by installing "libclang-8-dev".
Please let me know how to proceed.

Best,
Lukas

**Comment by aryamazaheri** [comment]
@aandergr, Would you please help @lukasrothenberger to fix the CI issues?

**Comment by aandergr** [comment]
> However, two checks are failing while building. The same error occured on my local machine and could be fixed by installing "libclang-8-dev".

This fix also worked in the CI workflow :)

**Comment by lukasrothenberger** [comment]
@aandergr 

Great, thank you very much!

**Comment by lukasrothenberger** [comment]
@aryamazaheri 

Hi Arya,
could you please have another look over the changes?

Thanks a lot!

**Review by aryamazaheri — APPROVED** [review]

**Pull request merged**
